-- RAG 数据表总入口。
-- 本地 compose.yaml 会把该目录挂载到 /docker-entrypoint-initdb.d，首次创建数据库时按文件名顺序自动执行。
-- 手动初始化时，可在 psql 中按顺序执行以下脚本：
--   \i 00_extensions.sql
--   \i 01_vector_store.sql
--   \i 02_paper_document.sql
--   \i 03_paper_document_chunk.sql
--
-- 本地运行：
--   docker compose up -d
--   copy src/main/resources/application-local.example.yaml src/main/resources/application-local.yaml
--   $env:DASHSCOPE_API_KEY="your-api-key"
--   mvn spring-boot:run
--
-- 上传验证：
--   curl -F "file=@sample.pdf" -F "sourceId=sample-paper" -F "title=Sample Paper" http://localhost:8080/documents
--
-- 问答验证：
--   curl -H "Content-Type: application/json" -d '{"question":"这篇论文的核心观点是什么？","topK":3}' http://localhost:8080/rag/ask
--
-- 注意：如果通过 Navicat 执行，请按文件名顺序逐个执行。