package com.lqr.papermind.document.structured;

import com.lqr.papermind.document.service.DocumentPersistenceService;
import com.lqr.papermind.document.structured.model.StructuredParseResult;
import com.lqr.papermind.document.structured.service.impl.PaperSectionRuleParserImpl;
import org.junit.jupiter.api.Test;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 论文结构化解析的章节规则识别测试。
 */
class PaperSectionRuleParserTest {

    private final PaperSectionRuleParserImpl parser = new PaperSectionRuleParserImpl();

    @Test
    void parseShouldRecognizeChineseNumberedSections() {
        String text = """
                关键词：RAG；论文评审；结构化解析
                摘要
                本文研究论文内容智能解析。
                一、引言
                介绍研究背景。
                二、文献综述
                梳理相关研究。
                三、研究方法
                采用规则与模型结合的方法。
                四、实验结果
                实验结果稳定。
                五、结论
                本文方法有效。
                参考文献
                [1] 示例文献。
                """;

        StructuredParseResult result = parser.parse(document("论文结构化解析研究", null, null, text));

        assertThat(result.content().title()).isEqualTo("论文结构化解析研究");
        assertThat(result.content().keywords()).containsExactly("RAG", "论文评审", "结构化解析");
        assertThat(result.content().abstractText()).contains("本文研究论文内容智能解析");
        assertThat(result.content().introduction()).contains("研究背景");
        assertThat(result.content().literatureReview()).contains("相关研究");
        assertThat(result.content().methodology()).contains("规则与模型结合");
        assertThat(result.content().experimentResults()).contains("实验结果稳定");
        assertThat(result.content().conclusion()).contains("方法有效");
        assertThat(result.content().references()).contains("示例文献");
    }

    @Test
    void parseShouldRecognizeEnglishSections() {
        String text = """
                Abstract
                This paper studies structured parsing.
                Keywords: paper review, parser
                1 Introduction
                Background text.
                2 Related Work
                Prior studies.
                3 Methodology
                Rule-based parsing first.
                4 Results
                Stable results.
                5 Discussion
                Practical limitations.
                6 Conclusion
                Main conclusion.
                References
                [1] Sample.
                """;

        StructuredParseResult result = parser.parse(document("English Paper", null, null, text));

        assertThat(result.content().abstractText()).contains("structured parsing");
        assertThat(result.content().keywords()).containsExactly("paper review", "parser");
        assertThat(result.content().introduction()).contains("Background text");
        assertThat(result.content().literatureReview()).contains("Prior studies");
        assertThat(result.content().methodology()).contains("Rule-based parsing first");
        assertThat(result.content().experimentResults()).contains("Stable results");
        assertThat(result.content().discussion()).contains("Practical limitations");
        assertThat(result.content().conclusion()).contains("Main conclusion");
    }

    @Test
    void parseShouldNotUseGeneratorMetadataAsAbstract() {
        String text = """
                摘要
                本文围绕后端分离博客系统展开设计与实现。
                1.1 项目背景
                本系统用于支持多角色博客管理。
                """;

        StructuredParseResult result = parser.parse(document("课程设计", "generated by python-docx", null, text));

        assertThat(result.content().abstractText()).contains("后端分离博客系统");
        assertThat(result.content().abstractText()).doesNotContain("python-docx");
    }

    @Test
    void parseShouldStopIntroductionAtUnknownNumberedHeading() {
        String text = """
                1.1 项目背景
                本系统面向博客内容管理。
                1.2 研究内容
                本文围绕用户、文章和分类进行设计。
                2 研究方法
                采用前后端分离架构。
                """;

        StructuredParseResult result = parser.parse(document("课程设计", null, null, text));

        assertThat(result.content().introduction()).contains("博客内容管理");
        assertThat(result.content().introduction()).doesNotContain("前后端分离架构");
        assertThat(result.content().methodology()).contains("前后端分离架构");
    }

    @Test
    void parseShouldRecognizeCourseDesignSectionNames() {
        String text = """
                相关技术
                本系统使用 Spring Boot 与 Vue。
                系统测试
                登录、文章发布和评论流程测试通过。
                总结与展望
                系统完成了主要功能。
                """;

        StructuredParseResult result = parser.parse(document("课程设计", null, null, text));

        assertThat(result.content().literatureReview()).contains("Spring Boot");
        assertThat(result.content().experimentResults()).contains("流程测试通过");
        assertThat(result.content().conclusion()).contains("主要功能");
    }

    @Test
    void parseShouldIgnoreContentsPageNumbersBeforeBodySections() {
        String text = """
                软件分析与建模技术课程设计

                1 引言1
                1.1 项目背景2
                1.2 研究内容3
                2 需求分析3
                2.1 业务分析3
                3 系统设计6
                4 系统测试18
                5 总结22

                1 引言
                本课程设计围绕博客系统展开。

                2 需求分析
                系统需要支持用户登录、文章管理和评论管理。

                3 系统设计
                系统采用 Spring Boot、Vue 3 和数据库建模。

                4 系统测试
                对登录、发布文章和评论流程进行测试。

                5 总结
                本文完成博客系统主要功能设计与实现。
                """;

        StructuredParseResult result = parser.parse(document("软件分析与建模技术课程设计", null, null, text));

        assertThat(result.content().introduction()).contains("课程设计围绕博客系统");
        assertThat(result.content().methodology()).contains("用户登录、文章管理和评论管理");
        assertThat(result.content().methodology()).doesNotContain("2.1 业务分析3");
        assertThat(result.content().experimentResults()).contains("登录、发布文章和评论流程");
        assertThat(result.content().conclusion()).contains("主要功能设计与实现");
    }

    @Test
    void parseShouldRecognizeHeadingsWithTrailingPageNumbers() {
        String text = """
                2 需求分析3
                系统需要支持用户登录、文章管理和评论管理。

                3 系统测试18
                对登录、发布文章和评论流程进行测试。

                5 总结22
                本文完成博客系统主要功能设计与实现。
                """;

        StructuredParseResult result = parser.parse(document("软件分析与建模技术课程设计", null, null, text));

        assertThat(result.content().methodology()).contains("用户登录、文章管理和评论管理");
        assertThat(result.content().experimentResults()).contains("发布文章和评论流程");
        assertThat(result.content().conclusion()).contains("博客系统主要功能");
    }

    private DocumentPersistenceService.DocumentDetail document(String title, String abstractText, Object keywords, String contentText) {
        OffsetDateTime now = OffsetDateTime.now();
        return new DocumentPersistenceService.DocumentDetail(
                "source-1",
                UUID.randomUUID(),
                title,
                "paper.pdf",
                "paper.pdf",
                "application/pdf",
                100L,
                List.of(),
                abstractText,
                null,
                null,
                null,
                keywords,
                contentText,
                Map.of(),
                "INDEXED",
                1,
                null,
                now,
                now,
                null
        );
    }
}
